version: '3.8'

services:
  # [MÁQUINA DE DESARROLLO] - Entrenamiento YOLO26
  cbn_train:
    image: localhost/neuralbottlescbn_cbn_train:latest
    build:
      context: .
      target: python_env
      args:
        GPU_BACKEND: cuda  # cpu | rocm | cuda
    shm_size: '8gb'
    working_dir: /workspace/ws_py
    volumes:
      - ./ws_py:/workspace/ws_py
      - ./ws_cpp/models:/workspace/ws_cpp/models
    # --- GPU NVIDIA ---
    devices:
      - nvidia.com/gpu=all

  # [MÁQUINA DE DESARROLLO] - Prueba de Inferencia C++ Local (Compilación Nativa)
  cbn_test_cpp:
    image: localhost/neuralbottlescbn_cbn_test_cpp:latest
    network_mode: host
    build:
      context: .
      target: cpp_base
    working_dir: /workspace/ws_cpp
    devices:
      - "/dev/video0:/dev/video0" # Ajuste según su cámara web
      - "/dev/gpiochip0:/dev/gpiochip0" # Ajuste según el super IO chip
    group_add:
      - video
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    ipc: host
    volumes:
      - ./ws_cpp:/workspace/ws_cpp
      - ./ws_py/dataset:/workspace/ws_py/dataset
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    command: /bin/bash -lc "mkdir -p build && cd build && cmake .. -G Ninja -DCMAKE_CXX_FLAGS='-O3 -march=native' && ninja main && ./main"

  # [MÁQUINA DE PRODUCCIÓN] - Inferencia Industrial
  cbn_edge:
    image: localhost/neuralbottles_edge:latest
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/gpiochip0:/dev/gpiochip0" # Ajuste según el super IO chip
    group_add:
      - video
    working_dir: /app
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    ipc: host
    volumes:
      - ./ws_cpp/models:/app/models:ro
      - ./ws_cpp/config:/app/config:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    restart: unless-stopped
