%YAML:1.0
---
camera_width: 1280
camera_height: 720
roi_x: 45
roi_y: 100
roi_width: 200
roi_height: 200
resize_enable: 1
resize_width: 320
resize_height: 240
grayscale_enable: 1
blur_enable: 1
blur_kernel_size: 7
clahe_enable: 0
clahe_clip_limit: 18
hist_eq_enable: 1
burst_recording_enable: 0
