%YAML:1.0
---
camera_width: 1280
camera_height: 720
roi_x: 35
roi_y: 43
roi_width: 13
roi_height: 17
resize_enable: 1
resize_width: 288
resize_height: 144
grayscale_enable: 1
blur_enable: 0
blur_kernel_size: 3
clahe_enable: 1
clahe_clip_limit: 40
hist_eq_enable: 0
burst_recording_enable: 0
