%YAML:1.0
---
# Rutas
model_path: "../models/cbn_model.xml"
labels_path: "../config/labels.yaml"

# Parametros de YOLO26
input_width: 640
input_height: 640
conf_threshold: 0.1
nms_threshold: 0.95

# Lógica del casillero (Business Rules)
target_total_slots: 12
target_cap_count: 12
